# Generated by Django 5.2.1 on 2026-03-10 11:33
# Updated on rename from 'logs' to 'activity_logs'

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration initiale de l'app activity_logs (anciennement 'logs').
    Sur DB existante (prod) la table porte le nom logs_activitylog et sera
    renommée par 0002_rename_table.
    Sur DB fraîche (tests / nouvelle installation) cette migration crée
    directement la table activity_logs_activitylog via la RunSQL conditionnelle.
    """

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='ActivityLog',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('OPEN', 'Ouverture'), ('CLOSE', 'Clôture'), ('TRANSFER', 'Transfert'), ('LOGIN', 'Connexion')], max_length=20)),
                        ('module', models.CharField(choices=[('factures', 'Factures'), ('caisse', 'Caisse'), ('commandes', 'Commandes'), ('approvisionnements', 'Approvisionnements'), ('stock', 'Stock'), ('auth', 'Authentification'), ('system', 'Système')], max_length=30)),
                        ('description', models.CharField(max_length=500)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                        ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': "Journal d'activité",
                        'verbose_name_plural': "Journal d'activités",
                        'ordering': ['-created_at'],
                    },
                ),
            ],
            # Sur DB fraîche : crée la table avec le nom définitif si elle n'existe pas encore.
            # Sur DB existante (avant renommage) : la table logs_activitylog est déjà là,
            # cette instruction est un no-op grâce au IF NOT EXISTS.
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS activity_logs_activitylog (
                            id          bigserial PRIMARY KEY,
                            action      varchar(20)  NOT NULL,
                            module      varchar(30)  NOT NULL,
                            description varchar(500) NOT NULL,
                            created_at  timestamptz  NOT NULL,
                            ip_address  inet,
                            user_id     bigint REFERENCES %(user_table)s (id)
                                            ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED
                        );
                    """ % {"user_table": "users_customuser"},
                    reverse_sql="DROP TABLE IF EXISTS activity_logs_activitylog;",
                ),
            ],
        ),
    ]
