# Generated by Django 5.2.1 on 2026-06-29 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0002_rename_table'),
    ]

    operations = []