# Generated by Django 5.2.1 on 2025-05-12 15:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('produits', '0004_stock_magasin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('date_facture', models.DateField(default=datetime.date.today)),
                ('devise', models.CharField(choices=[('$', '$'), ('FC', 'FC')], max_length=2)),
                ('taux', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('remise', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('client_comptoir', models.CharField(blank=True, max_length=30, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clients.client')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturecreepar', to=settings.AUTH_USER_MODEL)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturemodpar', to=settings.AUTH_USER_MODEL)),
                ('livreur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='factures.livreur')),
            ],
        ),
        migrations.CreateModel(
            name='DetailsFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.IntegerField()),
                ('prix', models.DecimalField(decimal_places=4, max_digits=8)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='produits.article')),
                ('facture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='factures.facture')),
            ],
        ),
    ]
