# Generated by Django 5.2.1 on 2025-05-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsfacture',
            name='date_peremption',
            field=models.DateField(blank=True, null=True),
        ),
    ]
