# Generated by Django 5.2.1 on 2025-05-23 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0002_detailsfacture_date_peremption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailsfacture',
            name='date_peremption',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='client',
        ),
    ]
