# Generated by Django 5.2.1 on 2025-05-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0003_remove_detailsfacture_date_peremption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livreur',
            name='livraison',
            field=models.IntegerField(default=0),
        ),
    ]
