# Generated by Django 5.2.1 on 2025-05-26 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0004_livreur_livraison'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsLigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.IntegerField()),
                ('date_peremption', models.DateField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('detail_facture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='factures.detailsfacture')),
            ],
        ),
    ]
