# Generated by Django 5.2.1 on 2025-08-21 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0005_detailslignefacture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsfacture',
            name='facture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facture_details', to='factures.facture'),
        ),
    ]
