# Generated by Django 5.2.1 on 2025-10-29 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_paiementclient'),
        ('factures', '0006_alter_detailsfacture_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='valide',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FactureClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facture_client', to='factures.facture')),
            ],
        ),
    ]
