# Generated by Django 5.2.1 on 2025-11-02 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0007_facture_valide_factureclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factureclient',
            name='facture',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='facture_client', to='factures.facture'),
        ),
    ]
