# Generated by Django 5.2.1 on 2025-11-27 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0008_alter_factureclient_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
