# Generated by Django 5.2.1 on 2025-11-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0009_alter_facture_remise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsfacture',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
