# Generated by Django 5.2.1 on 2026-06-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0011_delete_detailslignefacture'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='valeur_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
    ]
