# Generated by Django 5.2.1 on 2026-06-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0012_facture_valeur_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsfacture',
            name='taux_creation',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Taux de change historique au moment de la facture', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='detailsfacture',
            name='valeur_usd',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Valeur USD historique de cette ligne de facture', max_digits=14, null=True),
        ),
    ]
