# Generated by Django 5.2.1 on 2026-06-29 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0013_detailsfacture_taux_creation_and_more'),
        ('produits', '0013_merge_20260629_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsfacture',
            name='lot',
            field=models.ForeignKey(blank=True, help_text='Lot spécifique vendu (pour gestion des péremptions)', null=True, on_delete=django.db.models.deletion.PROTECT, to='produits.stock'),
        ),
    ]
