# Generated by Django 4.2.19 on 2025-03-27 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produits', '0002_alter_categorie_nom'),
        ('fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.IntegerField()),
                ('prix', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='produits.article')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('devise', models.CharField(choices=[('$', '$'), ('FC', 'FC')], max_length=2)),
                ('taux', models.DecimalField(decimal_places=4, default=0.0, max_digits=4)),
                ('date_commande', models.DateField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('fournisseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fournisseurs.fournisseur')),
            ],
        ),
    ]
