# Generated by Django 4.2.19 on 2025-03-27 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='cree_par',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='commandecreepar', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commande',
            name='modifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commandemodpar', to=settings.AUTH_USER_MODEL),
        ),
    ]
