# Generated by Django 4.2.19 on 2025-03-27 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0001_initial'),
        ('commandes', '0002_commande_cree_par_commande_modifie_par'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='fournisseur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='fournisseurs.fournisseur'),
            preserve_default=False,
        ),
    ]
