# Generated by Django 4.2.19 on 2025-03-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_alter_commande_fournisseur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='taux',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
        ),
    ]
