# Generated by Django 4.2.19 on 2025-03-28 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0007_alter_commande_taux'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailscommande',
            name='commande',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='commandes.commande'),
        ),
    ]
