# Generated by Django 5.2.1 on 2026-03-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0009_alter_commande_devise_taux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailscommande',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
