# Generated by Django 5.2.1 on 2026-03-24 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0010_alter_detailscommande_prix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={'ordering': ['-numero'], 'verbose_name': 'Commande', 'verbose_name_plural': 'Commandes'},
        ),
        migrations.AlterModelOptions(
            name='detailscommande',
            options={'verbose_name': 'Détail commande', 'verbose_name_plural': 'Détails commande'},
        ),
    ]
