# Generated by Django 5.2.1 on 2026-06-29 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_commande_statut'),
        ('commandes', '0011_alter_commande_options_alter_detailscommande_options'),
    ]

    operations = [
    ]
