# Generated by Django 5.2.1 on 2025-06-28 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0004_caissecourante_caisse'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caissier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caisse.caisse')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medecin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
