# Generated by Django 5.2.1 on 2026-03-11 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_caissier'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='force_password_change',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='typeprofile',
            name='slug',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='caissier',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caissier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='type_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='users.typeprofile'),
        ),
        migrations.AlterField(
            model_name='typeprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='typeprofile',
            name='nom',
            field=models.CharField(max_length=50),
        ),
    ]
