# Generated by Django 5.2.1 on 2026-03-11 10:50

import django.utils.text
from django.db import migrations, models

CANONICAL_ROLES = [
    ('admin', 'Administrateur', 'Accès complet à tous les modules'),
    ('facturier', 'Facturier', 'Gestion de la facturation et consultation des clients'),
    ('caissier', 'Caissier', 'Gestion de la trésorerie sur sa caisse propre'),
    ('gerant_stock', 'Gérant (Stock)', 'Consultation des stocks et mouvements en lecture seule'),
    ('gerant_magasin', 'Gérant de magasin', 'Accès opérationnel à la facturation, caisse, clients et stock'),
]

# Attempt to match legacy nom values to canonical slugs
LEGACY_NOM_MAP = {
    'admin': 'admin',
    'administrateur': 'admin',
    'facturier': 'facturier',
    'caissier': 'caissier',
    'gérant': 'gerant_stock',
    'gerant': 'gerant_stock',
    'gérant stock': 'gerant_stock',
    'gérant de magasin': 'gerant_magasin',
    'gérant magasin': 'gerant_magasin',
}


def seed_typeprofiles(apps, schema_editor):
    TypeProfile = apps.get_model('users', 'TypeProfile')

    # Assign slugs to any existing records without one
    for profile in TypeProfile.objects.filter(slug=''):
        guessed_slug = LEGACY_NOM_MAP.get(profile.nom.lower().strip())
        if guessed_slug:
            profile.slug = guessed_slug
        else:
            profile.slug = f'legacy_{django.utils.text.slugify(profile.nom)}_{profile.pk}'
        profile.save(update_fields=['slug'])

    # Create or update the 5 canonical roles
    for slug, nom, description in CANONICAL_ROLES:
        TypeProfile.objects.get_or_create(
            slug=slug,
            defaults={'nom': nom, 'description': description},
        )


def reverse_seed_typeprofiles(apps, schema_editor):
    TypeProfile = apps.get_model('users', 'TypeProfile')
    slugs = [slug for slug, _, _ in CANONICAL_ROLES]
    TypeProfile.objects.filter(slug__in=slugs).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_slug_to_typeprofile_and_force_password_change'),
    ]

    operations = [
        migrations.RunPython(seed_typeprofiles, reverse_seed_typeprofiles),
        migrations.AlterField(
            model_name='typeprofile',
            name='slug',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
