# Generated by Django 4.2.19 on 2025-04-12 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fournisseurs', '0001_initial'),
        ('produits', '0004_stock_magasin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parametres', '0002_magasin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approvisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('devise', models.CharField(choices=[('$', '$'), ('FC', 'FC')], max_length=2)),
                ('taux', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrivagecreepar', to=settings.AUTH_USER_MODEL)),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametres.magasin')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arrivagemodpar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetailsApprovisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facture', models.CharField(max_length=15)),
                ('declaration', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('transport', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('tva', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('manutention', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('autre_frais', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('qte', models.IntegerField()),
                ('prix', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('date_peremption', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('approvisionnement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='approvisionnements.approvisionnement')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='produits.article')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fournisseurs.fournisseur')),
            ],
        ),
    ]
