# Generated by Django 4.2.19 on 2025-04-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvisionnements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsapprovisionnement',
            name='autre_frais',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='detailsapprovisionnement',
            name='declaration',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='detailsapprovisionnement',
            name='manutention',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='detailsapprovisionnement',
            name='prix',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='detailsapprovisionnement',
            name='transport',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='detailsapprovisionnement',
            name='tva',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
    ]
