# Generated by Django 4.2.19 on 2025-04-28 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('approvisionnements', '0002_alter_detailsapprovisionnement_autre_frais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvisionnement',
            name='cree_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvisionnementcreepar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approvisionnement',
            name='modifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approvisionnementmodpar', to=settings.AUTH_USER_MODEL),
        ),
    ]
