# Generated by Django 4.2.19 on 2025-04-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvisionnements', '0003_alter_approvisionnement_cree_par_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsapprovisionnement',
            name='qte_details',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
