# Generated by Django 4.2.19 on 2025-04-28 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approvisionnements', '0004_detailsapprovisionnement_qte_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailsapprovisionnement',
            name='qte_details',
        ),
    ]
