# Generated by Django 5.2.1 on 2025-06-28 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approvisionnements', '0005_remove_detailsapprovisionnement_qte_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailsapprovisionnement',
            name='tva',
        ),
    ]
