# Generated by Django 5.2.1 on 2025-12-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvisionnements', '0006_remove_detailsapprovisionnement_tva'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailsapprovisionnement',
            old_name='manutention',
            new_name='chargement',
        ),
        migrations.AddField(
            model_name='detailsapprovisionnement',
            name='dechargement',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailsapprovisionnement',
            name='entreposage',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailsapprovisionnement',
            name='services',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
