# Generated by Django 5.2.1 on 2025-12-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvisionnements', '0007_rename_manutention_detailsapprovisionnement_chargement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsapprovisionnement',
            name='autre_frais',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='detailsapprovisionnement',
            name='chargement',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='detailsapprovisionnement',
            name='dechargement',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='detailsapprovisionnement',
            name='declaration',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='detailsapprovisionnement',
            name='entreposage',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='detailsapprovisionnement',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detailsapprovisionnement',
            name='services',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='detailsapprovisionnement',
            name='transport',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
