# Generated by Django 5.2.1 on 2026-01-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvisionnements', '0008_alter_detailsapprovisionnement_autre_frais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvisionnement',
            name='valide',
            field=models.BooleanField(default=False),
        ),
    ]
