# Generated by Django 5.2.1 on 2026-02-22 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvisionnements', '0009_approvisionnement_valide'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('icon', models.CharField(default='fa-money', max_length=50)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FraisApprovisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approvisionnements.detailsapprovisionnement')),
                ('type_frais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='approvisionnements.typefrais')),
            ],
        ),
    ]
