# Generated by Django 5.2.1 on 2026-02-22 21:29

from django.db import migrations


def create_default_frais(apps, schema_editor):
    TypeFrais = apps.get_model("approvisionnements", "TypeFrais")

    frais_list = [
        "Transport",
        "Chargement",
        "Déchargement",
        "Services",
        "Entreposage",
        "Déclaration",
        "Autres frais",
    ]

    for nom in frais_list:
        TypeFrais.objects.get_or_create(nom=nom)


def migrate_old_frais(apps, schema_editor):
    Details = apps.get_model("approvisionnements", "DetailsApprovisionnement")
    Frais = apps.get_model("approvisionnements", "FraisApprovisionnement")
    TypeFrais = apps.get_model("approvisionnements", "TypeFrais")

    mapping = {
        "transport": "Transport",
        "chargement": "Chargement",
        "dechargement": "Déchargement",
        "services": "Services",
        "entreposage": "Entreposage",
        "declaration": "Déclaration",
        "autre_frais": "Autres frais",
    }

    for detail in Details.objects.all():
        for field, frais_name in mapping.items():
            montant = getattr(detail, field, 0)

            if montant and montant > 0:
                type_frais = TypeFrais.objects.get(nom=frais_name)

                Frais.objects.create(
                    detail=detail,
                    type_frais=type_frais,
                    montant=montant
                )


class Migration(migrations.Migration):

    dependencies = [
        ('approvisionnements', '0010_typefrais_fraisapprovisionnement'),
    ]

    operations = [
        migrations.RunPython(create_default_frais),
        migrations.RunPython(migrate_old_frais),
    ]
