# Generated by Django 5.2.1 on 2026-02-22 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approvisionnements', '0011_migrate_old_frais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailsapprovisionnement',
            name='autre_frais',
        ),
        migrations.RemoveField(
            model_name='detailsapprovisionnement',
            name='chargement',
        ),
        migrations.RemoveField(
            model_name='detailsapprovisionnement',
            name='dechargement',
        ),
        migrations.RemoveField(
            model_name='detailsapprovisionnement',
            name='declaration',
        ),
        migrations.RemoveField(
            model_name='detailsapprovisionnement',
            name='entreposage',
        ),
        migrations.RemoveField(
            model_name='detailsapprovisionnement',
            name='services',
        ),
        migrations.RemoveField(
            model_name='detailsapprovisionnement',
            name='transport',
        ),
    ]
