# Generated by Django 5.2.1 on 2026-02-24 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvisionnements', '0012_remove_detailsapprovisionnement_autre_frais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraisapprovisionnement',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais', to='approvisionnements.detailsapprovisionnement'),
        ),
    ]
