# Generated by Django 5.2.1 on 2026-06-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvisionnements', '0013_alter_fraisapprovisionnement_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsapprovisionnement',
            name='taux_creation',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='detailsapprovisionnement',
            name='valeur_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='fraisapprovisionnement',
            name='taux_creation',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='fraisapprovisionnement',
            name='valeur_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
    ]
