# Generated by Django 5.2.1 on 2026-06-27 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produits', '0012_article_derniere_sync_firestore_article_est_publie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcommerceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('evenement', models.CharField(choices=[('sync_article', 'Synchronisation article'), ('sync_stock', 'Synchronisation stock'), ('import_commande', 'Import commande'), ('erreur_sync', 'Erreur synchronisation'), ('erreur_import', 'Erreur import')], max_length=50)),
                ('article_code', models.CharField(blank=True, max_length=50, null=True)),
                ('commande_id', models.CharField(blank=True, max_length=100, null=True)),
                ('success', models.BooleanField()),
                ('message', models.TextField(blank=True)),
                ('duree_ms', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['evenement', 'timestamp'], name='ecommerce_e_eveneme_4cfb1a_idx'), models.Index(fields=['commande_id'], name='ecommerce_e_command_ea8db7_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImageArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_originale', models.ImageField(upload_to='articles/originaux/')),
                ('image_webp_600', models.ImageField(blank=True, upload_to='articles/webp/600x600/')),
                ('image_webp_150', models.ImageField(blank=True, upload_to='articles/webp/150x150/')),
                ('est_principale', models.BooleanField(default=False)),
                ('ordre', models.IntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='produits.article')),
            ],
            options={
                'verbose_name': "Image d'article",
                'verbose_name_plural': "Images d'articles",
                'ordering': ['-est_principale', 'ordre', 'date_creation'],
            },
        ),
        migrations.CreateModel(
            name='SyncQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('tentatives', models.IntegerField(default=0)),
                ('erreur', models.TextField(blank=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.article')),
            ],
            options={
                'ordering': ['date_creation'],
            },
        ),
    ]
