# Generated by Django 4.2.19 on 2025-02-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='Params', max_length=6)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('sigle', models.CharField(blank=True, max_length=30, null=True)),
                ('societe', models.CharField(blank=True, max_length=40, null=True)),
                ('rccm', models.CharField(blank=True, max_length=40, null=True)),
                ('idnat', models.CharField(blank=True, max_length=40, null=True)),
                ('impot', models.CharField(blank=True, max_length=40, null=True)),
                ('tva', models.CharField(blank=True, max_length=50, null=True)),
                ('pays', models.CharField(blank=True, max_length=30, null=True)),
                ('adresse', models.CharField(blank=True, max_length=150, null=True)),
                ('ville', models.CharField(blank=True, max_length=30, null=True)),
                ('telephone', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
