# Generated by Django 4.2.19 on 2025-03-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('is_principal', models.BooleanField(default=False)),
                ('localisation', models.CharField(max_length=30)),
            ],
        ),
    ]
