# Generated by Django 5.2.1 on 2026-02-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0002_magasin'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametre',
            name='taux',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
