# Generated by Django 5.2.1 on 2026-03-08 17:57

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0004_remove_parametre_taux'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTauxEchange',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('devise_source', models.CharField(choices=[('USD', 'Dollar US'), ('CDF', 'Franc Congolais')], default='USD', max_length=3, verbose_name='Devise source')),
                ('devise_cible', models.CharField(choices=[('USD', 'Dollar US'), ('CDF', 'Franc Congolais')], default='CDF', max_length=3, verbose_name='Devise cible')),
                ('taux', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Taux')),
                ('effective_date', models.DateField(help_text='Date à partir de laquelle ce taux est applicable.', verbose_name="Date d'application")),
                ('date_creation', models.DateTimeField(blank=True, editable=False)),
                ('date_modification', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "historical Taux d'échange",
                'verbose_name_plural': "historical Taux d'échange",
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TauxEchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devise_source', models.CharField(choices=[('USD', 'Dollar US'), ('CDF', 'Franc Congolais')], default='USD', max_length=3, verbose_name='Devise source')),
                ('devise_cible', models.CharField(choices=[('USD', 'Dollar US'), ('CDF', 'Franc Congolais')], default='CDF', max_length=3, verbose_name='Devise cible')),
                ('taux', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Taux')),
                ('effective_date', models.DateField(help_text='Date à partir de laquelle ce taux est applicable.', verbose_name="Date d'application")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Taux d'échange",
                'verbose_name_plural': "Taux d'échange",
                'ordering': ['-effective_date'],
                'constraints': [models.UniqueConstraint(fields=('devise_source', 'devise_cible', 'effective_date'), name='unique_rate_per_day')],
            },
        ),
    ]
