# Generated by Django 5.2.1 on 2026-01-06 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caisse', '0010_alter_mouvementcaisse_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotJournalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_entrees', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_sorties', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('solde_ouverture', models.DecimalField(decimal_places=2, max_digits=14)),
                ('solde_fermeture', models.DecimalField(decimal_places=2, max_digits=14)),
                ('est_cloture', models.BooleanField(default=False)),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caisse.caisse')),
            ],
            options={
                'unique_together': {('date', 'caisse')},
            },
        ),
        migrations.CreateModel(
            name='SnapshotMensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('mois', models.IntegerField()),
                ('total_entrees', models.DecimalField(decimal_places=2, max_digits=16)),
                ('total_sorties', models.DecimalField(decimal_places=2, max_digits=16)),
                ('solde_fin_mois', models.DecimalField(decimal_places=2, max_digits=16)),
                ('est_cloture', models.BooleanField(default=False)),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caisse.caisse')),
            ],
            options={
                'unique_together': {('annee', 'mois', 'caisse')},
            },
        ),
    ]
