# Generated by Django 5.2.1 on 2026-01-21 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvisionnements', '0008_alter_detailsapprovisionnement_autre_frais_and_more'),
        ('patrimoine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultatJournalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('resultat_brut', models.DecimalField(decimal_places=2, max_digits=14)),
                ('chiffre_affaires', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultatApprovisionnementSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('devise', models.CharField(max_length=2)),
                ('taux', models.DecimalField(decimal_places=2, max_digits=6)),
                ('resultat_brut', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cout_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('chiffre_affaires', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('approvisionnement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='approvisionnements.approvisionnement')),
            ],
        ),
        migrations.CreateModel(
            name='ResultatMensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('resultat_brut', models.DecimalField(decimal_places=2, max_digits=14)),
                ('chiffre_affaires', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('mois', 'annee')},
            },
        ),
    ]
