# Generated by Django 5.2.1 on 2026-01-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimoine', '0002_resultatjournalier_resultatapprovisionnementsnapshot_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultatapprovisionnementsnapshot',
            old_name='cout_total',
            new_name='cout_achat',
        ),
        migrations.AddField(
            model_name='resultatapprovisionnementsnapshot',
            name='frais_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
            preserve_default=False,
        ),
    ]
