# Generated by Django 5.2.1 on 2026-03-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimoine', '0003_rename_cout_total_resultatapprovisionnementsnapshot_cout_achat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FondsRoulementSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('fr_initial', models.DecimalField(decimal_places=2, max_digits=16)),
                ('ej', models.DecimalField(decimal_places=2, max_digits=16)),
                ('sj', models.DecimalField(decimal_places=2, max_digits=16)),
                ('fr_final', models.DecimalField(decimal_places=2, max_digits=16)),
                ('fr_contreverif', models.DecimalField(decimal_places=2, max_digits=16)),
                ('ecart', models.DecimalField(decimal_places=2, max_digits=16)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
