# Generated by Django 5.2.1 on 2026-03-11 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimoine', '0004_add_fonds_roulement_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fondsroulementsnapshot',
            name='valide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fondsroulementsnapshot',
            name='valide_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fondsroulementsnapshot',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_fr', to=settings.AUTH_USER_MODEL),
        ),
    ]
