# Generated by Django 5.2.1 on 2026-06-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimoine', '0005_fondsroulement_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='fondsroulementsnapshot',
            name='ej_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='fondsroulementsnapshot',
            name='fr_final_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='fondsroulementsnapshot',
            name='fr_initial_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='fondsroulementsnapshot',
            name='sj_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='fondsroulementsnapshot',
            name='taux_jour',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Taux USD/FC du jour', max_digits=12, null=True),
        ),
    ]
