# Generated by Django 5.2.1 on 2026-06-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimoine', '0006_fondsroulementsnapshot_ej_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultatapprovisionnementsnapshot',
            name='chiffre_affaires_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='resultatapprovisionnementsnapshot',
            name='cout_achat_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='resultatapprovisionnementsnapshot',
            name='frais_achat_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='resultatapprovisionnementsnapshot',
            name='resultat_brut_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='resultatjournalier',
            name='chiffre_affaires_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='resultatjournalier',
            name='resultat_brut_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='resultatmensuel',
            name='chiffre_affaires_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='resultatmensuel',
            name='resultat_brut_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
    ]
