# Generated by Django 5.2.1 on 2026-06-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimoine', '0007_resultatapprovisionnementsnapshot_chiffre_affaires_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshotjournalier',
            name='solde_fermeture_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
    ]
