# Generated by Django 4.2.19 on 2025-04-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('photo', models.ImageField(blank=True, upload_to='clients/')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('adresse', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=150)),
                ('ville', models.CharField(max_length=30)),
            ],
        ),
    ]
