# Generated by Django 5.2.1 on 2025-11-27 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_paiementclient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaiementClient',
        ),
    ]
