# Generated by Django 5.2.1 on 2025-08-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.IntegerField(unique=True)),
                ('photo', models.ImageField(blank=True, upload_to='agents/')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('adresse', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=150)),
                ('ville', models.CharField(max_length=30)),
            ],
        ),
    ]
