# Generated by Django 5.2.1 on 2025-10-13 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0002_agent_salaire_paie_detailspaie'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='date_engagement',
            field=models.DateField(default=datetime.datetime(2025, 10, 13, 7, 34, 51, 540961)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='date_naissance',
            field=models.DateField(default=datetime.datetime(2025, 10, 13, 7, 35, 9, 196207)),
            preserve_default=False,
        ),
    ]
