# Generated by Django 5.2.1 on 2025-10-13 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0003_agent_date_engagement_agent_date_naissance'),
    ]

    operations = [
        migrations.AddField(
            model_name='paie',
            name='absence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paie',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='agent_paie_details', to='paie.agent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paie',
            name='jap',
            field=models.IntegerField(default=26),
        ),
        migrations.AddField(
            model_name='paie',
            name='jp',
            field=models.IntegerField(default=26),
        ),
        migrations.AddField(
            model_name='paie',
            name='montant_percu',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paie',
            name='salaire',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DetailsPaie',
        ),
    ]
