# Generated by Django 5.2.1 on 2025-10-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0004_paie_absence_paie_agent_paie_jap_paie_jp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paie',
            name='salaire',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
