# Generated by Django 5.2.1 on 2025-10-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0005_alter_paie_salaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paie',
            name='montant_percu',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paie',
            name='salaire',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
