# Generated by Django 5.2.1 on 2025-10-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0006_alter_paie_montant_percu_alter_paie_salaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='salaire',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
