# Generated by Django 5.2.1 on 2026-03-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0009_paie_restructure_lignepaie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['nom'], 'verbose_name': 'Agent', 'verbose_name_plural': 'Agents'},
        ),
        migrations.AlterModelOptions(
            name='paie',
            options={'ordering': ['-mois', 'agent__nom'], 'verbose_name': 'Paie', 'verbose_name_plural': 'Paies'},
        ),
        migrations.AlterField(
            model_name='agent',
            name='salaire',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
