# Generated by Django 5.2.1 on 2026-06-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0010_alter_agent_options_alter_paie_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignepaie',
            name='taux_creation',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Taux de change au moment de la création', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='lignepaie',
            name='valeur_usd',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Valeur USD historique de cette ligne (immuable)', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='paie',
            name='taux_creation',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Taux de change historique au moment de la création', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='paie',
            name='valeur_usd',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Valeur USD du net à payer (historique, immuable)', max_digits=14, null=True),
        ),
    ]
