# Generated by Django 5.2.1 on 2025-11-27 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0002_paiementfournisseur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaiementFournisseur',
        ),
    ]
