# Generated by Django 5.2.1 on 2026-02-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0003_delete_paiementfournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
