# Generated by Django 5.2.1 on 2026-02-22 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvisionnements', '0012_remove_detailsapprovisionnement_autre_frais_and_more'),
        ('fournisseurs', '0004_fournisseur_actif_fournisseur_is_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='type_frais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='approvisionnements.typefrais'),
        ),
    ]
