# Generated by Django 5.2.1 on 2025-06-17 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RubriqueCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='mouvementcaisse',
            name='rubrique',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_rubrique', to='caisse.rubriquecaisse'),
            preserve_default=False,
        ),
    ]
