# Generated by Django 5.2.1 on 2025-06-27 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0002_rubriquecaisse_mouvementcaisse_rubrique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caisse',
            name='date_fermeture',
        ),
        migrations.RemoveField(
            model_name='caisse',
            name='date_ouverture',
        ),
        migrations.RemoveField(
            model_name='caisse',
            name='est_ouverte',
        ),
        migrations.RemoveField(
            model_name='caisse',
            name='ferme_par',
        ),
        migrations.RemoveField(
            model_name='caisse',
            name='ouvert_par',
        ),
        migrations.RemoveField(
            model_name='caisse',
            name='solde_final',
        ),
        migrations.RemoveField(
            model_name='caisse',
            name='solde_initial',
        ),
        migrations.AddField(
            model_name='caisse',
            name='is_principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caisse',
            name='nom',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CaisseCourante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ouverture', models.DateTimeField(auto_now_add=True)),
                ('date_fermeture', models.DateTimeField(blank=True, null=True)),
                ('solde_initial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('solde_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('est_ouverte', models.BooleanField(default=True)),
                ('ferme_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fermetures_caisse', to=settings.AUTH_USER_MODEL)),
                ('ouvert_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ouvertures_caisse', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='mouvementcaisse',
            name='caisse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='caisse.caissecourante'),
        ),
    ]
