# Generated by Django 5.2.1 on 2025-06-28 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0003_remove_caisse_date_fermeture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caissecourante',
            name='caisse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='caisses', to='caisse.caisse'),
            preserve_default=False,
        ),
    ]
