# Generated by Django 5.2.1 on 2025-07-11 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0004_caissecourante_caisse'),
        ('clients', '0002_paiementclient'),
        ('creanciers', '0001_initial'),
        ('fournisseurs', '0002_paiementfournisseur'),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementCaisseClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='clients.client')),
                ('mouvement_caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_caisse_c', to='caisse.mouvementcaisse')),
            ],
        ),
        migrations.CreateModel(
            name='MouvementCaisseCreancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creancier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creancier', to='creanciers.creancier')),
                ('mouvement_caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_caisse_cr', to='caisse.mouvementcaisse')),
            ],
        ),
        migrations.CreateModel(
            name='MouvementCaisseFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fournisseur', to='fournisseurs.fournisseur')),
                ('mouvement_caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_caisse_f', to='caisse.mouvementcaisse')),
            ],
        ),
    ]
