# Generated by Django 5.2.1 on 2025-10-13 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0005_mouvementcaisseclient_mouvementcaissecreancier_and_more'),
        ('paie', '0002_agent_salaire_paie_detailspaie'),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementCaisseAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='paie.agent')),
                ('mouvement_caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_caisse_ag', to='caisse.mouvementcaisse')),
            ],
        ),
    ]
