# Generated by Django 5.2.1 on 2025-11-08 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0006_mouvementcaisseagent'),
        ('creanciers', '0002_debiteur_alter_creancier_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementCaisseDebiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debiteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debiteur', to='creanciers.debiteur')),
                ('mouvement_caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_caisse_db', to='caisse.mouvementcaisse')),
            ],
        ),
    ]
