# Generated by Django 5.2.1 on 2025-12-17 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0007_mouvementcaissedebiteur'),
    ]

    operations = [
        migrations.CreateModel(
            name='SousRubriqueCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('rubrique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_rubriques', to='caisse.rubriquecaisse')),
            ],
        ),
    ]
