# Generated by Django 5.2.1 on 2025-12-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0008_sousrubriquecaisse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sousrubriquecaisse',
            name='nom',
            field=models.CharField(max_length=45),
        ),
    ]
