# Generated by Django 5.2.1 on 2026-01-06 08:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0009_alter_sousrubriquecaisse_nom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mouvementcaisse',
            options={'ordering': ['date_mouvement']},
        ),
        migrations.AddIndex(
            model_name='mouvementcaisse',
            index=models.Index(fields=['date_mouvement'], name='caisse_mouv_date_mo_816de8_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementcaisse',
            index=models.Index(fields=['type_mouvement'], name='caisse_mouv_type_mo_53d3f5_idx'),
        ),
    ]
