# Generated by Django 5.2.1 on 2026-02-24 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0011_mouvementcaissechargesexploitation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementcaisse',
            name='sous_rubrique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='caisse.sousrubriquecaisse'),
        ),
    ]
