# Generated by Django 5.2.1 on 2026-03-10 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0012_mouvementcaisse_sous_rubrique'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementcaisse',
            name='caisse_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_sortants', to='caisse.caisse'),
        ),
    ]
