# Generated by Django 5.2.1 on 2026-03-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0014_add_transfer_link_to_mouvementcaisse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caissecourante',
            name='solde_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='caissecourante',
            name='solde_initial',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='mouvementcaisse',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
