# Generated by Django 5.2.1 on 2026-06-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0016_rubriquecaisse_classification_metier'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementcaisseclient',
            name='taux_paiement',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='mouvementcaisseclient',
            name='valeur_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='mouvementcaissecreancier',
            name='taux_paiement',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='mouvementcaissecreancier',
            name='valeur_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='mouvementcaissedebiteur',
            name='taux_paiement',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='mouvementcaissedebiteur',
            name='valeur_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='mouvementcaissefournisseur',
            name='taux_paiement',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='mouvementcaissefournisseur',
            name='valeur_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
    ]
