# Generated by Django 5.2.1 on 2026-06-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0017_mouvementcaisseclient_taux_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caissecourante',
            name='solde_final_usd',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Valeur USD du solde final au taux de fermeture', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='caissecourante',
            name='solde_initial_usd',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Valeur USD du solde initial au taux d'ouverture", max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='caissecourante',
            name='taux_fermeture',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Taux historique à la fermeture', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='caissecourante',
            name='taux_ouverture',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Taux historique à l'ouverture", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='mouvementcaisse',
            name='montant_usd',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Valeur USD historique du mouvement', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='mouvementcaisse',
            name='taux_mouvement',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Taux de change historique au moment du mouvement', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='mouvementcaisseagent',
            name='taux_paiement',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Taux historique au moment du paiement', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='mouvementcaisseagent',
            name='valeur_usd',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Valeur USD historique du paiement', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='mouvementcaissechargesexploitation',
            name='taux_mouvement',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Taux historique au moment de la charge', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='mouvementcaissechargesexploitation',
            name='valeur_usd',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Valeur USD historique de la charge', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='mouvementcaissechargespersonnelles',
            name='taux_mouvement',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Taux historique au moment de la charge', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='mouvementcaissechargespersonnelles',
            name='valeur_usd',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Valeur USD historique de la charge', max_digits=14, null=True),
        ),
    ]
