# Generated by Django 5.2.1 on 2025-11-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creanciers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('photo', models.ImageField(blank=True, upload_to='debiteurs/')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('adresse', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=150)),
                ('ville', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='creancier',
            name='photo',
            field=models.ImageField(blank=True, upload_to='creanciers/'),
        ),
    ]
