# Generated by Django 4.2.19 on 2025-02-20 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('designation', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField()),
                ('code_barre', models.CharField(max_length=35)),
                ('prix_achat', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('prix_vente', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('prix_vente_gros', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('devise', models.CharField(choices=[('$', '$'), ('FC', 'FC')], max_length=2)),
                ('seuil', models.IntegerField()),
                ('seuil_gros', models.IntegerField()),
                ('emplacement', models.CharField(max_length=150)),
                ('photo1', models.ImageField(blank=True, upload_to='articles/')),
                ('photo2', models.ImageField(blank=True, upload_to='articles/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.IntegerField()),
                ('date_peremption', models.DateField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produits.article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produits.categorie'),
        ),
        migrations.AddField(
            model_name='article',
            name='fournisseur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fournisseurs.fournisseur'),
        ),
        migrations.AddField(
            model_name='article',
            name='unite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produits.unite'),
        ),
    ]
