# Generated by Django 4.2.19 on 2025-03-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='nom',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
