# Generated by Django 4.2.19 on 2025-03-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_alter_categorie_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='qte',
            field=models.IntegerField(default=0),
        ),
    ]
