# Generated by Django 4.2.19 on 2025-03-31 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0002_magasin'),
        ('produits', '0003_alter_stock_qte'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='magasin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='parametres.magasin'),
            preserve_default=False,
        ),
    ]
