# Generated by Django 5.2.1 on 2025-11-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0004_stock_magasin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='prix_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='article',
            name='prix_vente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='article',
            name='prix_vente_gros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
