# Generated by Django 5.2.1 on 2025-12-15 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0005_alter_article_prix_achat_alter_article_prix_vente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='code_barre',
        ),
    ]
