# Generated by Django 5.2.1 on 2026-01-26 09:51

import django.db.models.deletion
from django.db import migrations, models

from parametres.models import Magasin


def forwards_func(apps, schema_editor):
    MouvementStock = apps.get_model("produits", "MouvementStock")
    DetailsAppro = apps.get_model("approvisionnements", "DetailsApprovisionnement")
    DetailsFact = apps.get_model("factures", "DetailsFacture")
    Magasin = apps.get_model("parametres", "Magasin")

    # ENTRÉES
    for d in DetailsAppro.objects.select_related("article", "approvisionnement__magasin"):
        MouvementStock.objects.create(
            magasin=d.approvisionnement.magasin,
            article=d.article,
            type="IN",
            qte=d.qte,
            date_peremption=d.date_peremption,
            source_type="Approvisionnement",
            source_id=d.approvisionnement.id,
            date_creation=d.date_creation,
        )

    # SORTIES
    magasin_principal = Magasin.objects.get(is_principal=True)

    for d in DetailsFact.objects.select_related("article"):
        MouvementStock.objects.create(
            magasin=magasin_principal,
            article=d.article,
            type="OUT",
            qte=d.qte,
            source_type="Facture",
            source_id=d.facture.id,
            date_creation=d.date_creation,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0002_magasin'),
        ('produits', '0006_remove_article_code_barre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsommationLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_peremption', models.DateField(blank=True, null=True)),
                ('qte', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IN', 'Entrée'), ('OUT', 'Sortie')], max_length=3)),
                ('qte', models.PositiveIntegerField()),
                ('date_peremption', models.DateField(blank=True, null=True)),
                ('source_type', models.CharField(max_length=50)),
                ('source_id', models.PositiveIntegerField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransfertStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.PositiveIntegerField()),
                ('date_peremption', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('valide', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('magasin', 'article', 'date_peremption'), name='unique_lot_stock'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('qte__gte', 0)), name='stock_non_negatif'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produits.article'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='magasin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametres.magasin'),
        ),
        migrations.AddField(
            model_name='consommationlot',
            name='mouvement_sortie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots_consommés', to='produits.mouvementstock'),
        ),
        migrations.AddField(
            model_name='transfertstock',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produits.article'),
        ),
        migrations.AddField(
            model_name='transfertstock',
            name='magasin_destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_entrants', to='parametres.magasin'),
        ),
        migrations.AddField(
            model_name='transfertstock',
            name='magasin_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_sortants', to='parametres.magasin'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['magasin', 'article'], name='produits_mo_magasin_20637b_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['article', 'date_peremption'], name='produits_mo_article_c6a3c5_idx'),
        ),
        migrations.AddConstraint(
            model_name='mouvementstock',
            constraint=models.CheckConstraint(condition=models.Q(('qte__gt', 0)), name='qte_positive'),
        ),
        # migrations.RunPython(forwards_func),
    ]
