# Generated by Django 5.2.1 on 2026-01-26 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0007_consommationlot_mouvementstock_transfertstock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfertstock',
            name='article',
        ),
        migrations.RemoveField(
            model_name='transfertstock',
            name='date_peremption',
        ),
        migrations.RemoveField(
            model_name='transfertstock',
            name='qte',
        ),
        migrations.AddField(
            model_name='transfertstock',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transfertstock',
            name='cree_par',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='transfertcreepar', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfertstock',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transfertstock',
            name='modifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfertmodpar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfertstock',
            name='numero',
            field=models.IntegerField(default=260000, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DetailsTransfertStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.PositiveIntegerField()),
                ('date_peremption', models.DateField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produits.article')),
                ('transfert_stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produits.transfertstock')),
            ],
        ),
    ]
