# Generated by Django 5.2.1 on 2026-02-20 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0008_remove_transfertstock_article_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailstransfertstock',
            old_name='transfert_stock',
            new_name='transfert',
        ),
        migrations.AlterField(
            model_name='detailstransfertstock',
            name='date_peremption',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='ReservationTransfertLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_peremption', models.DateField()),
                ('qte', models.PositiveIntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produits.article')),
                ('transfert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.transfertstock')),
            ],
        ),
        migrations.DeleteModel(
            name='ConsommationLot',
        ),
    ]
