# Generated by Django 5.2.1 on 2026-02-21 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0009_rename_transfert_stock_detailstransfertstock_transfert_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailstransfertstock',
            name='date_peremption',
        ),
    ]
