# Generated by Django 5.2.1 on 2026-03-02 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0010_remove_detailstransfertstock_date_peremption'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementstock',
            name='annule_mouvement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compensatoires', to='produits.mouvementstock'),
        ),
    ]
