# Generated by Django 5.2.1 on 2026-06-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0011_mouvementstock_annule_mouvement'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='derniere_sync_firestore',
            field=models.DateTimeField(blank=True, help_text='Timestamp de la dernière sync réussie vers Firestore', null=True, verbose_name='Dernière synchronisation Firestore'),
        ),
        migrations.AddField(
            model_name='article',
            name='est_publie',
            field=models.BooleanField(default=False, help_text="Si True, l'article apparaît sur la boutique en ligne", verbose_name='Publié en ligne'),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL SEO générée automatiquement depuis le nom', max_length=250, null=True, unique=True),
        ),
    ]
