# Generated by Django 5.2.1 on 2026-06-29 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0012_article_derniere_sync_firestore_article_est_publie_and_more'),
    ]

    operations = [
    ]
