# Generated by Django 5.2.1 on 2026-06-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0013_merge_20260629_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='frais_approche',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Frais d'approche (FA) - Transport, douane, assurance, etc.", max_digits=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='prix_achat',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Prix d'achat net (PAN) - Prix unitaire payé au fournisseur", max_digits=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='prix_vente_detail',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Prix de vente détail (PVD) - Prix unitaire en détail', max_digits=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='prix_vente_gros',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Prix de vente gros (PVG) - Prix unitaire en gros', max_digits=10),
        ),
    ]
